server:
  port: 8080
  servlet:
      context-path: /bootcamp


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://uhmxtdbchsnwda:3577e090fe7a776cf5da19fe146078012fe6592a66e8edb6bb8d3a24d17f9aca@ec2-23-23-128-222.compute-1.amazonaws.com:5432/d8teraa5eo7qeq
    username: uhmxtdbchsnwda
    password: 3577e090fe7a776cf5da19fe146078012fe6592a66e8edb6bb8d3a24d17f9aca

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Bootcamp FullStack Santander na Santander Week - Backend. Por Juliana Akemi.
  version: 2.0